import { getTypeMove, tierForLevel } from './typeMoves.js'

const baseCache = new Map()

// Resolved evolution outcome per species id: null = no level-up evolution
// (final stage / non-level trigger), or { speciesId, minLevel } for the next
// stage. One chain load fills the whole evolutionary line, so repeat
// checkEvolution calls after every battle cost zero network.
const evoCache = new Map()
// Pruned evolution-chain root (shape: { id, evolvesTo: [{ id, minLevel,
// evolvesTo }] } — level-up branches only) cached per species id, so
// checkEvolution and resolveEvolutionLine share a single chain per line.
const chainCache = new Map()

// ── Local bundled data ──────────────────────────────────────────────────
// public/data/pokedex.json + public/data/evolutions.json are generated by
// `npm run build:dex` (scripts/buildPokedex.mjs) from the region configs and
// cover every species the game can reference. Loading them makes the whole
// game run without live pokeapi.co calls; anything NOT covered still falls
// back to the live network paths below. Loaded once, lazily, on first use.
let localDataPromise = null
function ensureLocalData() {
  if (!localDataPromise) {
    localDataPromise = (async () => {
      try {
        const [dexRes, evoRes] = await Promise.all([
          fetch('/data/pokedex.json'),
          fetch('/data/evolutions.json'),
        ])
        if (dexRes.ok) {
          const { pokemon } = await dexRes.json()
          for (const entry of Object.values(pokemon)) {
            const result = {
              pokeId: entry.pokeId,
              name: displayName(entry.apiName),
              types: entry.types,
              baseStats: entry.baseStats,
              sprite: entry.sprite,
              spriteBack: entry.spriteBack,
              shinySprite: entry.shinySprite,
              shinySpriteBack: entry.shinySpriteBack,
            }
            // Key by id, raw API name, and display name so every lookup style
            // (numeric id, 'tornadus-incarnate', 'tornadus') resolves.
            baseCache.set(result.pokeId, result)
            baseCache.set(entry.apiName, result)
            baseCache.set(result.name, result)
          }
        }
        if (evoRes.ok) {
          const { chains, speciesToRoot } = await evoRes.json()
          for (const [id, rootId] of Object.entries(speciesToRoot)) {
            const chain = chains[rootId]
            if (chain) chainCache.set(Number(id), chain)
          }
        }
      } catch {
        // Local data unavailable (e.g. build:dex never ran) — every lookup
        // falls through to the live PokéAPI paths, exactly as before.
      }
    })()
  }
  return localDataPromise
}

// PokéAPI returns some species with a default-forme suffix, e.g.
// "tornadus-incarnate", "keldeo-ordinary". For display we want just the base
// species name ("tornadus", "keldeo"). We strip only these known forme
// suffixes so legitimately hyphenated names (mr-mime, ho-oh, nidoran-f,
// porygon-z, type-null, etc.) are left untouched.
const FORME_SUFFIXES = [
  '-incarnate',    // Tornadus, Thundurus, Landorus
  '-ordinary',     // Keldeo
  '-aria',         // Meloetta
  '-standard',     // Darmanitan
  '-red-striped',  // Basculin
  '-blue-striped', // Basculin
]

export function displayName(name) {
  if (!name) return name
  for (const suffix of FORME_SUFFIXES) {
    if (name.endsWith(suffix)) return name.slice(0, -suffix.length)
  }
  return name
}

// Pre-fetch base + move data for every Pokémon ID a region config references so
// all subsequent node activations are served from cache with no network delay.
// Everything is read off the region config — the loop stays region-agnostic.
export async function prewarmCache(regionConfig) {
  const ids = new Set()

  // Catch pools (per-map arrays of { id, rarity })
  regionConfig.catchPools?.forEach(pool => pool.forEach(m => ids.add(m.id)))
  // Trainer pools (per-map arrays of ids)
  regionConfig.trainerSpeciesPools?.forEach(pool => pool.forEach(id => ids.add(id)))
  // Themed per-class trainer pools ({ [trainerName]: [baseFormId] })
  Object.values(regionConfig.trainerTypePools ?? {}).forEach(pool => pool.forEach(id => ids.add(id)))
  // Boss teams + Elite Four teams (keyed by trainer name → [{ id, level }])
  Object.values(regionConfig.bossTeams ?? {}).forEach(team => team.forEach(({ id }) => ids.add(id)))
  Object.values(regionConfig.eliteFourTeams ?? {}).forEach(team => team.forEach(({ id }) => ids.add(id)))
  // Rival teams (keyed by variant → [{ id, level }])
  Object.values(regionConfig.rivalTeams ?? {}).forEach(team => team.forEach(({ id }) => ids.add(id)))
  // Legendary (Master Ball) pools (per-map arrays of { id, level })
  regionConfig.legendaryPools?.forEach(pool => pool.forEach(({ id }) => ids.add(id)))

  // Species that get an evolution-stage roll at click time (catch nodes + themed
  // trainer pools). Warming their whole line up front means late-map clicks
  // never block on a live chain fetch + evolved-form base fetch.
  const stageRolled = new Set()
  regionConfig.catchPools?.forEach(pool => pool.forEach(m => stageRolled.add(m.id)))
  Object.values(regionConfig.trainerTypePools ?? {}).forEach(pool => pool.forEach(id => stageRolled.add(id)))

  // First warm the directly-referenced bases.
  await Promise.all([...ids].map(async id => {
    try { await fetchPokemonBase(id) } catch { /* live-fetch fallback */ }
  }))

  // Then warm each stage-rolled line: the evolution chain (side effect of
  // allSpeciesInLine) plus every evolved-form base in the tree.
  await Promise.all([...stageRolled].map(async id => {
    try {
      const lineIds = await allSpeciesInLine(id)
      await Promise.all(lineIds.map(async lid => {
        try { await fetchPokemonBase(lid) } catch { /* live-fetch fallback */ }
      }))
    } catch { /* non-fatal — node falls back to live fetch */ }
  }))
}

// Read a prewarmed species' primary type / display name straight from the base
// cache (populated by prewarmCache before a map renders). Used by node tooltips
// so we don't hand-maintain per-region id→type / id→name tables. Returns null if
// the id hasn't been fetched yet (callers show a placeholder).
export function cachedType(id) {
  return baseCache.get(id)?.types?.[0] ?? null
}

export function cachedName(id) {
  return baseCache.get(id)?.name ?? null
}

// Pure stat formula (Gen 5, 31 IVs, neutral nature, 0 EVs)
export function calcHP(base, level) {
  return Math.floor(((2 * base + 31) * level) / 100) + level + 10
}

export function calcStat(base, level) {
  return Math.floor(((2 * base + 31) * level) / 100) + 5
}

// Fetch base data for a Pokémon by id or name. Reads from the local bundled
// Pokédex first (see ensureLocalData); only species it doesn't cover hit
// PokéAPI live. Returns a plain object with everything needed to build a
// battle-ready instance.
export async function fetchPokemonBase(idOrName) {
  if (baseCache.has(idOrName)) return baseCache.get(idOrName)
  await ensureLocalData()
  if (baseCache.has(idOrName)) return baseCache.get(idOrName)
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${idOrName}`)
  if (!res.ok) throw new Error(`PokéAPI error for ${idOrName}`)
  const data = await res.json()

  const result = {
    pokeId: data.id,
    name: displayName(data.name),
    types: data.types.map(t => t.type.name),
    baseStats: {
      hp:      data.stats.find(s => s.stat.name === 'hp').base_stat,
      attack:  data.stats.find(s => s.stat.name === 'attack').base_stat,
      defense: data.stats.find(s => s.stat.name === 'defense').base_stat,
      spAtk:   data.stats.find(s => s.stat.name === 'special-attack').base_stat,
      spDef:   data.stats.find(s => s.stat.name === 'special-defense').base_stat,
      speed:   data.stats.find(s => s.stat.name === 'speed').base_stat,
    },
    sprite: data.sprites.front_default,
    spriteBack: data.sprites.back_default ?? data.sprites.front_default,
    shinySprite: data.sprites.front_shiny ?? data.sprites.front_default,
    shinySpriteBack: data.sprites.back_shiny ?? data.sprites.back_default ?? data.sprites.front_shiny ?? data.sprites.front_default,
  }
  baseCache.set(idOrName, result)
  baseCache.set(result.pokeId, result)
  return result
}

// Shiny encounter rate. Every spawned Pokémon rolls once — so a caught wild or
// legendary can be shiny (and shiny enemies just look shiny in battle).
export const SHINY_ODDS = 1 / 512

// Build a full battle-ready Pokémon instance from base data + level.
// The move is the Pokémon's primary-type tiered move; tier is set by level on spawn.
export function buildPokemonInstance(base, level, isStarter = false) {
  const boost = isStarter ? 1.3 : 1
  const hp = Math.floor(calcHP(base.baseStats.hp, level) * boost)
  const move = getTypeMove(base.types[0], tierForLevel(level))
  const shiny = Math.random() < SHINY_ODDS
  return {
    pokeId:     base.pokeId,
    name:       base.name,
    types:      base.types,
    level,
    shiny,
    sprite:     shiny ? base.shinySprite : base.sprite,
    spriteBack: shiny ? base.shinySpriteBack : base.spriteBack,
    stats: {
      maxHp:   hp,
      hp,
      attack:  Math.floor(calcStat(base.baseStats.attack,  level) * boost),
      defense: Math.floor(calcStat(base.baseStats.defense, level) * boost),
      spAtk:   Math.floor(calcStat(base.baseStats.spAtk,   level) * boost),
      spDef:   Math.floor(calcStat(base.baseStats.spDef,   level) * boost),
      speed:   Math.floor(calcStat(base.baseStats.speed,   level) * boost),
    },
    move,
    fainted: false,
    _base: base,
  }
}

// Prune a raw PokéAPI chain node to the shape the game consumes: only level-up
// evolutions with a min_level survive (item/trade/etc. branches are dropped —
// the game never offers or evolves into forms the player couldn't level into).
//   { id, evolvesTo: [{ id, minLevel, evolvesTo: [...] }] }
// Must match the pruning in scripts/buildPokedex.mjs.
function pruneChain(node) {
  const id = Number(node.species.url.match(/\/(\d+)\/?$/)?.[1])
  const evolvesTo = []
  for (const child of node.evolves_to ?? []) {
    const detail = (child.evolution_details ?? []).find(d =>
      d.trigger?.name === 'level-up' && d.min_level != null
    )
    if (!detail) continue
    evolvesTo.push({
      id: Number(child.species.url.match(/\/(\d+)\/?$/)?.[1]),
      minLevel: detail.min_level,
      evolvesTo: pruneChain(child).evolvesTo,
    })
  }
  return { id, evolvesTo }
}

// Resolve a Pokémon's pruned evolution-chain root — from the local bundled
// data when available, else from live PokéAPI (raw chain pruned on ingest).
// Cached under every species id in the line so any member resolves without
// another lookup. Returns null on failure (leaves cache unset so a later call
// can retry).
async function loadEvolutionChain(pokeId) {
  if (chainCache.has(pokeId)) return chainCache.get(pokeId)
  await ensureLocalData()
  if (chainCache.has(pokeId)) return chainCache.get(pokeId)

  const speciesRes = await fetch(`https://pokeapi.co/api/v2/pokemon-species/${pokeId}`)
  if (!speciesRes.ok) return null
  const species = await speciesRes.json()

  const chainRes = await fetch(species.evolution_chain.url)
  if (!chainRes.ok) return null
  const chainData = await chainRes.json()

  // Cache the shared pruned root under every species id in the RAW line (even
  // members whose own branches were pruned away) so any member resolves
  // without another fetch.
  const pruned = pruneChain(chainData.chain)
  const register = node => {
    const id = Number(node.species.url.match(/\/(\d+)\/?$/)?.[1])
    if (id) chainCache.set(id, pruned)
    node.evolves_to.forEach(register)
  }
  register(chainData.chain)
  return pruned
}

// Resolve a Pokémon's evolution chain and cache the (next-stage) outcome for
// every species in it. Failures leave the cache unset so a later call can
// retry. Only the first (level-up) branch evolves — matches prior behavior.
async function loadEvolutionLine(pokeId) {
  const chain = await loadEvolutionChain(pokeId)
  if (!chain) return

  const walk = node => {
    if (node.id) {
      const next = node.evolvesTo[0] ?? null
      evoCache.set(node.id, next ? { speciesId: next.id, minLevel: next.minLevel } : null)
    }
    node.evolvesTo.forEach(walk)
  }
  walk(chain)
}

// Every species id reachable by LEVEL-UP evolution from a Pokémon (all
// branches of the pruned tree), warming chainCache as a side effect. Used by
// prewarmCache to fetch evolved-form bases up front so late-map node clicks
// never block on a live fetch. Returns [] on failure (the base id is still
// usable on its own).
export async function allSpeciesInLine(pokeId) {
  const root = await loadEvolutionChain(pokeId)
  if (!root) return []
  const ids = []
  const walk = node => {
    if (node.id) ids.push(node.id)
    node.evolvesTo.forEach(walk)
  }
  walk(root)
  return ids
}

// Resolve a species' full evolutionary line as an ordered list of stages, from
// the base form forward. Each stage is { id, minLevel } where minLevel is the
// cumulative level a caught Pokémon must be to legitimately be at that stage
// (base = 1). Branches are followed randomly, matching the "random branch"
// catch-node design. Returns [] on failure (caller falls back to the pool's
// own id). Used only by catch nodes — grass/trainers are untouched.
export async function resolveEvolutionLine(pokeId) {
  const root = await loadEvolutionChain(pokeId)
  if (!root) return []

  const stages = []
  let node = root
  let cumulativeLevel = 1
  while (node) {
    if (!node.id) break
    stages.push({ id: node.id, minLevel: cumulativeLevel })
    // Branches are pre-filtered to level-up evolutions (see pruneChain), so
    // any of them is a form the player could have leveled into.
    if (node.evolvesTo.length === 0) break
    const nextNode = node.evolvesTo[Math.floor(Math.random() * node.evolvesTo.length)]
    // Cumulative: a later stage can't be reached below its own evolution level.
    cumulativeLevel = Math.max(cumulativeLevel, nextNode.minLevel)
    node = nextNode
  }
  return stages
}

// Given a base-form species id and a level, return the id of the evolution stage
// to actually use. Resolves the full line, keeps stages whose evolution level is
// ≤ level, and picks one weighted toward the most-evolved (weight = stage index
// + 1). Falls back to the original id if the line can't be resolved. Shared by
// catch nodes (offered wild Pokémon) and themed trainer teams so both gate
// evolution by level identically.
export async function rollStageForLevel(id, level) {
  let stages
  try {
    stages = await resolveEvolutionLine(id)
  } catch {
    return id
  }
  if (!stages || stages.length === 0) return id
  const eligible = stages.filter(s => s.minLevel <= level)
  if (eligible.length === 0) return stages[0].id
  const total = eligible.reduce((s, _, i) => s + (i + 1), 0)
  let roll = Math.random() * total
  for (let i = 0; i < eligible.length; i++) {
    roll -= i + 1
    if (roll <= 0) return eligible[i].id
  }
  return eligible[eligible.length - 1].id
}

// Check if a Pokémon should evolve after reaching newLevel.
// Returns the evolved PokémonInstance or null.
export async function checkEvolution(instance, newLevel) {
  try {
    if (!evoCache.has(instance.pokeId)) {
      await loadEvolutionLine(instance.pokeId)
    }
    const next = evoCache.get(instance.pokeId)
    if (!next || newLevel < next.minLevel) return null

    // Evolve — fetch new base and rebuild instance
    const evolvedBase = await fetchPokemonBase(next.speciesId)
    const hpRatio = instance.stats.hp / instance.stats.maxHp
    const evolved = buildPokemonInstance(evolvedBase, newLevel)
    // Preserve HP ratio
    const evolvedHp = Math.max(1, Math.floor(evolved.stats.maxHp * hpRatio))
    // Preserve the Pokémon's current move tier across evolution (set via TM nodes,
    // not by level), using the evolved Pokémon's primary type.
    const preservedTier = instance.move?.tier ?? tierForLevel(newLevel)
    // Shininess carries through evolution — keep the flag and the matching sprites.
    const shiny = !!instance.shiny
    return {
      ...evolved,
      shiny,
      sprite:     shiny ? evolvedBase.shinySprite : evolvedBase.sprite,
      spriteBack: shiny ? evolvedBase.shinySpriteBack : evolvedBase.spriteBack,
      stats: { ...evolved.stats, hp: evolvedHp },
      move: getTypeMove(evolvedBase.types[0], preservedTier),
      // Carry the held item through evolution (buildPokemonInstance omits it).
      heldItem: instance.heldItem ?? null,
      fainted: instance.fainted,
    }
  } catch {
    return null
  }
}

// Apply a battle victory to the sim's final team: level-ups, the 5% survivor
// heal, an optional full heal + revive (boss wins), then evolution checks.
// Returns { roster, evolutionNotices } where notices are { from, to, pokeId } —
// Pokédex "owned" recording stays at the call site.
export async function applyBattleVictory(finalPlayerTeam, { levelsGained = 2, fullHeal = false } = {}) {
  let roster = finalPlayerTeam.map(fp => fp._base ? levelUp(fp, fp._base, levelsGained) : fp)
  // Victory heal: every surviving Pokémon recovers 5% of max HP (capped).
  roster = roster.map(p =>
    p.fainted ? p
      : { ...p, stats: { ...p.stats, hp: Math.min(p.stats.maxHp, p.stats.hp + Math.round(p.stats.maxHp * 0.05)) } }
  )
  if (fullHeal) {
    roster = roster.map(p => ({ ...p, fainted: false, stats: { ...p.stats, hp: p.stats.maxHp } }))
  }

  const evolutionNotices = []
  roster = await Promise.all(roster.map(async p => {
    const evolved = await checkEvolution(p, p.level)
    if (evolved) {
      evolutionNotices.push({ from: p.name, to: evolved.name, pokeId: evolved.pokeId })
      return evolved
    }
    return p
  }))
  return { roster, evolutionNotices }
}

// Level up a Pokémon instance — recalculates stats only.
// The move never changes on level-up; only a TM / Power Upgrade node changes it.
export function levelUp(instance, base, levels) {
  const newLevel = instance.level + levels
  const newHp = calcHP(base.baseStats.hp, newLevel)
  const hpDiff = newHp - instance.stats.maxHp
  return {
    ...instance,
    level: newLevel,
    stats: {
      ...instance.stats,
      maxHp:   newHp,
      // Leveling raises max HP but must not revive a fainted Pokémon.
      hp:      instance.fainted ? 0 : Math.min(instance.stats.hp + hpDiff, newHp),
      attack:  calcStat(base.baseStats.attack,  newLevel),
      defense: calcStat(base.baseStats.defense, newLevel),
      spAtk:   calcStat(base.baseStats.spAtk,   newLevel),
      spDef:   calcStat(base.baseStats.spDef,   newLevel),
      speed:   calcStat(base.baseStats.speed,   newLevel),
    },
  }
}
