import { getTypeMove, tierForLevel } from './typeMoves.js'
import { attackTypeFor, alternateTypeFor } from './attackTypes.js'
import { slimChain, speciesIdFromUrl, levelUpPathTo, downgradeTarget } from './evolutionChain.js'
import { BALANCE } from './balance.js'
import { rng } from './rng.js'

const baseCache = new Map()

// Resolved evolution branches per species id: [{ id, minLevel, levelUp }]
// (empty array = no evolution). One chain load fills the whole evolutionary
// line, so repeat checkEvolution calls after every battle cost zero network.
const evoCache = new Map()
// Slimmed evolution-chain root (shape: { id, evolvesTo: [{ id, minLevel,
// levelUp, evolvesTo }] } — ALL branches, flagged level-up or not) cached per
// species id, so checkEvolution and resolveEvolutionLine share one chain per
// line.
const chainCache = new Map()

// Highest species id per generation. Evolution options are limited to species
// that exist in the run region's generation (config.generation) — e.g. a
// Kanto (gen 1) Eevee can't become Espeon (gen 2).
export const GEN_MAX_ID = { 1: 151, 2: 251, 3: 386, 4: 493, 5: 649, 6: 721, 7: 809, 8: 905, 9: 1025 }

// Species whose NON-level-up evolutions (stone/trade/friendship in the real
// games) still evolve automatically at battle victory. Everything else that
// evolves by a non-level trigger — Pikachu, Kadabra, Haunter, Golbat, Onix,
// Machoke, etc. — evolves ONLY via the Evolve Stone item (checkEvolution's
// `ignoreLevel` path). Eevee is the one intended exception: it should branch
// naturally through the EvolutionChoice popup.
//
// The bundled evolutions.json only records `levelUp: true/false` (the real
// trigger was discarded on build), so this allowlist is how we single Eevee
// out from the other non-level-up evolvers.
// Allowlist + threshold live in game/balance.js (BALANCE.pokemon).
export const AUTO_EVOLVE_NONLEVEL = new Set(BALANCE.pokemon.autoEvolveNonLevel)

// Level at which an allowlisted non-level-up evolution (see AUTO_EVOLVE_NONLEVEL)
// becomes available at battle victory. Non-allowlisted species ignore this and
// never auto-evolve — they need the Evolve Stone.
export const NON_LEVEL_EVO_LEVEL = BALANCE.pokemon.nonLevelEvoLevel

// ── Local bundled data ──────────────────────────────────────────────────
// public/data/pokedex.json + public/data/evolutions.json are generated by
// `npm run build:dex` (scripts/buildPokedex.mjs) from the region configs and
// cover every species the game can reference. Loading them makes the whole
// game run without live pokeapi.co calls; anything NOT covered still falls
// back to the live network paths below. Loaded once, lazily, on first use.
let localDataPromise = null
function ensureLocalData() {
  if (!localDataPromise) {
    localDataPromise = (async () => {
      try {
        const [dexRes, evoRes] = await Promise.all([
          fetch('/data/pokedex.json'),
          fetch('/data/evolutions.json'),
        ])
        if (dexRes.ok) {
          const { pokemon } = await dexRes.json()
          for (const entry of Object.values(pokemon)) {
            const result = {
              pokeId: entry.pokeId,
              name: displayName(entry.apiName),
              types: entry.types,
              baseStats: entry.baseStats,
              sprite: entry.sprite,
              spriteBack: entry.spriteBack,
              shinySprite: entry.shinySprite,
              shinySpriteBack: entry.shinySpriteBack,
            }
            // Key by id, raw API name, and display name so every lookup style
            // (numeric id, 'tornadus-incarnate', 'tornadus') resolves.
            baseCache.set(result.pokeId, result)
            baseCache.set(entry.apiName, result)
            baseCache.set(result.name, result)
          }
        }
        if (evoRes.ok) {
          const { chains, speciesToRoot } = await evoRes.json()
          for (const [id, rootId] of Object.entries(speciesToRoot)) {
            const chain = chains[rootId]
            if (chain) chainCache.set(Number(id), chain)
          }
        }
      } catch {
        // Local data unavailable (e.g. build:dex never ran) — every lookup
        // falls through to the live PokéAPI paths, exactly as before.
      }
    })()
  }
  return localDataPromise
}

// PokéAPI returns some species with a default-forme suffix, e.g.
// "tornadus-incarnate", "keldeo-ordinary". For display we want just the base
// species name ("tornadus", "keldeo"). We strip only these known forme
// suffixes so legitimately hyphenated names (mr-mime, ho-oh, nidoran-f,
// porygon-z, type-null, etc.) are left untouched.
const FORME_SUFFIXES = [
  '-incarnate',    // Tornadus, Thundurus, Landorus
  '-ordinary',     // Keldeo
  '-aria',         // Meloetta
  '-standard',     // Darmanitan
  '-red-striped',  // Basculin
  '-blue-striped', // Basculin
]

export function displayName(name) {
  if (!name) return name
  for (const suffix of FORME_SUFFIXES) {
    if (name.endsWith(suffix)) return name.slice(0, -suffix.length)
  }
  return name
}

// Pre-fetch base + move data for every Pokémon ID a region config references so
// all subsequent node activations are served from cache with no network delay.
// Everything is read off the region config — the loop stays region-agnostic.
export async function prewarmCache(regionConfig) {
  const ids = new Set()

  // Catch pools (per-map arrays of { id, rarity })
  regionConfig.catchPools?.forEach(pool => pool.forEach(m => ids.add(m.id)))
  // Trainer pools (per-map arrays of ids)
  regionConfig.trainerSpeciesPools?.forEach(pool => pool.forEach(id => ids.add(id)))
  // Themed per-class trainer pools ({ [trainerName]: [baseFormId] })
  Object.values(regionConfig.trainerTypePools ?? {}).forEach(pool => pool.forEach(id => ids.add(id)))
  // Boss teams + Elite Four teams (keyed by trainer name → [{ id, level }])
  Object.values(regionConfig.bossTeams ?? {}).forEach(team => team.forEach(({ id }) => ids.add(id)))
  Object.values(regionConfig.eliteFourTeams ?? {}).forEach(team => team.forEach(({ id }) => ids.add(id)))
  // Rival teams (keyed by variant → [{ id, level }])
  Object.values(regionConfig.rivalTeams ?? {}).forEach(team => team.forEach(({ id }) => ids.add(id)))
  // Starter-counter aces (rival nodes + the champion) — spliced in at battle
  // time, so they aren't in the team arrays above. All branches warm: the
  // player's starter isn't known here.
  Object.values(regionConfig.rivalStarterCounters ?? {}).forEach(counter =>
    Object.values(counter).forEach(({ id }) => ids.add(id)))
  Object.values(regionConfig.blueStarterCounter ?? {}).forEach(({ id }) => ids.add(id))
  // Legendary (Master Ball) pools (per-map arrays of { id, level })
  regionConfig.legendaryPools?.forEach(pool => pool.forEach(({ id }) => ids.add(id)))

  // Species that get an evolution-stage roll at click time (catch nodes + themed
  // trainer pools). Warming their whole line up front means late-map clicks
  // never block on a live chain fetch + evolved-form base fetch.
  const stageRolled = new Set()
  regionConfig.catchPools?.forEach(pool => pool.forEach(m => stageRolled.add(m.id)))
  Object.values(regionConfig.trainerTypePools ?? {}).forEach(pool => pool.forEach(id => stageRolled.add(id)))

  // First warm the directly-referenced bases.
  await Promise.all([...ids].map(async id => {
    try { await fetchPokemonBase(id) } catch { /* live-fetch fallback */ }
  }))

  // Then warm each stage-rolled line: the evolution chain (side effect of
  // allSpeciesInLine) plus every evolved-form base in the tree.
  await Promise.all([...stageRolled].map(async id => {
    try {
      const lineIds = await allSpeciesInLine(id)
      await Promise.all(lineIds.map(async lid => {
        try { await fetchPokemonBase(lid) } catch { /* live-fetch fallback */ }
      }))
    } catch { /* non-fatal — node falls back to live fetch */ }
  }))
}

// Read a prewarmed species' primary type / display name straight from the base
// cache (populated by prewarmCache before a map renders). Used by node tooltips
// so we don't hand-maintain per-region id→type / id→name tables. Returns null if
// the id hasn't been fetched yet (callers show a placeholder).
export function cachedType(id) {
  return baseCache.get(id)?.types?.[0] ?? null
}

export function cachedName(id) {
  return baseCache.get(id)?.name ?? null
}

// Hard level ceiling. The stat formulas below are only defined up to 100, and
// a full run (8 maps + Elite Four at +1/+2/+4 levels per win) overshoots it, so
// levelUp clamps here.
export const MAX_LEVEL = BALANCE.pokemon.maxLevel

// Pure stat formula (Gen 5, 31 IVs, neutral nature, 0 EVs)
export function calcHP(base, level) {
  return Math.floor(((2 * base + 31) * level) / 100) + level + 10
}

export function calcStat(base, level) {
  return Math.floor(((2 * base + 31) * level) / 100) + 5
}

// Fetch base data for a Pokémon by id or name. Reads from the local bundled
// Pokédex first (see ensureLocalData); only species it doesn't cover hit
// PokéAPI live. Returns a plain object with everything needed to build a
// battle-ready instance.
export async function fetchPokemonBase(idOrName) {
  if (baseCache.has(idOrName)) return baseCache.get(idOrName)
  await ensureLocalData()
  if (baseCache.has(idOrName)) return baseCache.get(idOrName)
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${idOrName}`)
  if (!res.ok) throw new Error(`PokéAPI error for ${idOrName}`)
  const data = await res.json()

  const result = {
    pokeId: data.id,
    name: displayName(data.name),
    types: data.types.map(t => t.type.name),
    baseStats: {
      hp:      data.stats.find(s => s.stat.name === 'hp').base_stat,
      attack:  data.stats.find(s => s.stat.name === 'attack').base_stat,
      defense: data.stats.find(s => s.stat.name === 'defense').base_stat,
      spAtk:   data.stats.find(s => s.stat.name === 'special-attack').base_stat,
      spDef:   data.stats.find(s => s.stat.name === 'special-defense').base_stat,
      speed:   data.stats.find(s => s.stat.name === 'speed').base_stat,
    },
    sprite: data.sprites.front_default,
    spriteBack: data.sprites.back_default ?? data.sprites.front_default,
    shinySprite: data.sprites.front_shiny ?? data.sprites.front_default,
    shinySpriteBack: data.sprites.back_shiny ?? data.sprites.back_default ?? data.sprites.front_shiny ?? data.sprites.front_default,
  }
  baseCache.set(idOrName, result)
  baseCache.set(result.pokeId, result)
  return result
}

// Shiny encounter rate. Every spawned Pokémon rolls once — so a caught wild or
// legendary can be shiny (and shiny enemies just look shiny in battle).
export const SHINY_ODDS = BALANCE.pokemon.shinyOdds

// Build a full battle-ready Pokémon instance from base data + level.
// The move is the Pokémon's primary-type tiered move; tier is set by level on spawn.
// `forceShiny` skips the roll and uses the given value. Only the starter needs
// it: StarterSelect builds preview instances to render the three choices, then
// App.initRoster rebuilds the chosen one to apply the 1.3× starter boost. Left
// to roll again, that rebuild would decide shininess a SECOND time — so the
// shiny Charmander you picked could arrive normal, and a normal one could
// arrive shiny. Passing the preview's flag through makes the sprite on the
// select screen a promise. Everything else passes nothing and rolls once.
export function buildPokemonInstance(base, rawLevel, isStarter = false, forceShiny = null) {
  // Clamp here too, not just in levelUp: this is the single constructor for
  // every instance (spawns, evolutions, enemy teams), so nothing can enter the
  // game above MAX_LEVEL regardless of what a caller passes.
  const level = Math.min(MAX_LEVEL, Math.max(1, rawLevel))
  const boost = isStarter ? BALANCE.pokemon.starterBoost : 1
  const hp = Math.floor(calcHP(base.baseStats.hp, level) * boost)
  const move = getTypeMove(attackTypeFor(base.pokeId, base.types), tierForLevel(level))
  // Null (not false) means "no opinion, roll it" — so an explicit false can
  // still force a non-shiny without being mistaken for an absent argument.
  const shiny = forceShiny === null ? rng() < SHINY_ODDS : !!forceShiny
  return {
    pokeId:     base.pokeId,
    name:       base.name,
    types:      base.types,
    level,
    shiny,
    sprite:     shiny ? base.shinySprite : base.sprite,
    spriteBack: shiny ? base.shinySpriteBack : base.spriteBack,
    stats: {
      maxHp:   hp,
      hp,
      attack:  Math.floor(calcStat(base.baseStats.attack,  level) * boost),
      defense: Math.floor(calcStat(base.baseStats.defense, level) * boost),
      spAtk:   Math.floor(calcStat(base.baseStats.spAtk,   level) * boost),
      spDef:   Math.floor(calcStat(base.baseStats.spDef,   level) * boost),
      speed:   Math.floor(calcStat(base.baseStats.speed,   level) * boost),
    },
    move,
    fainted: false,
    _base: base,
  }
}

// Resolve a Pokémon's slimmed evolution-chain root — from the local bundled
// data when available, else from live PokéAPI (raw chain slimmed on ingest).
// Cached under every species id in the line so any member resolves without
// another lookup. Returns null on failure (leaves cache unset so a later call
// can retry).
async function loadEvolutionChain(pokeId) {
  if (chainCache.has(pokeId)) return chainCache.get(pokeId)
  await ensureLocalData()
  if (chainCache.has(pokeId)) return chainCache.get(pokeId)

  const speciesRes = await fetch(`https://pokeapi.co/api/v2/pokemon-species/${pokeId}`)
  if (!speciesRes.ok) return null
  const species = await speciesRes.json()

  const chainRes = await fetch(species.evolution_chain.url)
  if (!chainRes.ok) return null
  const chainData = await chainRes.json()

  // Cache the shared root under every species id in the RAW line so any
  // member resolves without another fetch.
  const root = slimChain(chainData.chain)
  const register = node => {
    const id = speciesIdFromUrl(node.species.url)
    if (id) chainCache.set(id, root)
    node.evolves_to.forEach(register)
  }
  register(chainData.chain)
  return root
}

// Resolve a Pokémon's evolution chain and cache the branch list for every
// species in it. Failures leave the cache unset so a later call can retry.
async function loadEvolutionLine(pokeId) {
  const chain = await loadEvolutionChain(pokeId)
  if (!chain) return

  const walk = node => {
    if (node.id) {
      evoCache.set(node.id, node.evolvesTo.map(b => ({ id: b.id, minLevel: b.minLevel, levelUp: b.levelUp })))
    }
    node.evolvesTo.forEach(walk)
  }
  walk(chain)
}

// Every species id in a Pokémon's evolution tree (all branches, level-up or
// not), warming chainCache as a side effect. Used by prewarmCache to fetch
// evolved-form bases up front so late-map node clicks never block on a live
// fetch. Returns [] on failure (the base id is still usable on its own).
export async function allSpeciesInLine(pokeId) {
  const root = await loadEvolutionChain(pokeId)
  if (!root) return []
  const ids = []
  const walk = node => {
    if (node.id) ids.push(node.id)
    node.evolvesTo.forEach(walk)
  }
  walk(root)
  return ids
}

// Resolve a species' full evolutionary line as an ordered list of stages, from
// the base form forward. Each stage is { id, minLevel } where minLevel is the
// cumulative level a caught Pokémon must be to legitimately be at that stage
// (base = 1). Branches are followed randomly, matching the "random branch"
// catch-node design. Returns [] on failure (caller falls back to the pool's
// own id). Used only by catch nodes — grass/trainers are untouched.
//
// `maxSpeciesId` gates branches to the run region's generation, exactly as
// checkEvolution does. Without it a Gen-1 pool species can walk into a regional
// form from a later gen (PokéAPI files every form under one species id, so
// Meowth's chain lists both Persian and Galarian Perrserker as level-up
// branches, and Mr. Mime's ONLY level-up branch is Gen-8 Mr. Rime).
//
// `level`, when given, self-corrects an UNDER-LEVELED request: if pokeId's own
// cumulative level-up requirement exceeds `level` (e.g. a themed pool names
// Palpitoad, which needs L25, on an early map whose band tops out at L10),
// walk DOWN pokeId's level-up path to the most-evolved stage that level can
// legitimately reach, and resolve forward from THERE instead. This only fires
// when pokeId is reachable by a pure level-up path from its line's root —
// species behind a trade/stone/friendship step (Escavalier from Karrablast,
// Pikachu from Pichu) have no such path and are left exactly where the pool
// named them, at any level: that is the existing deliberate-floor case (see
// below) and downgrading it would silently swap a trade-evolution mon for its
// pre-evolution, which is wrong at every level, not just low ones.
export async function resolveEvolutionLine(pokeId, maxSpeciesId = Infinity, level) {
  const root = await loadEvolutionChain(pokeId)
  if (!root) return []

  let effectiveId = pokeId
  if (level != null) {
    const path = levelUpPathTo(root, pokeId)
    if (path) effectiveId = downgradeTarget(path, level)
  }

  // Start at the REQUESTED (or, if downgraded, the reachable) species, not the
  // chain root. A pool entry partway up a line (e.g. Pikachu, whose root is
  // Pichu) is a deliberate floor — walking from the root would offer the
  // pre-evolution the pool didn't ask for, and for non-level-up steps like
  // Pichu→Pikachu the walk below would stop dead there and *only* ever yield
  // Pichu.
  const findNode = node => {
    if (node.id === effectiveId) return node
    for (const child of node.evolvesTo ?? []) {
      const hit = findNode(child)
      if (hit) return hit
    }
    return null
  }
  const start = findNode(root) ?? root

  const stages = []
  let node = start
  let cumulativeLevel = 1
  while (node) {
    if (!node.id) break
    stages.push({ id: node.id, minLevel: cumulativeLevel })
    // Pick a random branch among LEVEL-UP evolutions; a stage is only
    // reachable by catching if it evolves by level (item/trade branches are
    // skipped so we never offer a form the player couldn't have leveled into).
    // Out-of-generation branches are dropped so the region stays canonical.
    const branches = node.evolvesTo.filter(b => b.levelUp && b.id <= maxSpeciesId)
    if (branches.length === 0) break
    const nextNode = branches[Math.floor(rng() * branches.length)]
    // Cumulative: a later stage can't be reached below its own evolution level.
    cumulativeLevel = Math.max(cumulativeLevel, nextNode.minLevel)
    node = nextNode
  }
  return stages
}

// Given a base-form species id and a level, return the id of the evolution stage
// to actually use. Resolves the full line, keeps stages whose evolution level is
// ≤ level, and picks one weighted toward the most-evolved (weight = stage index
// + 1). Falls back to the original id if the line can't be resolved. Shared by
// catch nodes (offered wild Pokémon) and themed trainer teams so both gate
// evolution by level identically. Pass `maxSpeciesId`
// (GEN_MAX_ID[config.generation]) to keep offers inside the region's gen.
export async function rollStageForLevel(id, level, maxSpeciesId = Infinity) {
  let stages
  try {
    stages = await resolveEvolutionLine(id, maxSpeciesId, level)
  } catch {
    return id
  }
  if (!stages || stages.length === 0) return id
  const eligible = stages.filter(s => s.minLevel <= level)
  if (eligible.length === 0) return stages[0].id
  const total = eligible.reduce((s, _, i) => s + (i + 1), 0)
  let roll = rng() * total
  for (let i = 0; i < eligible.length; i++) {
    roll -= i + 1
    if (roll <= 0) return eligible[i].id
  }
  return eligible[eligible.length - 1].id
}

// Rebuild an instance as its evolved form: fresh stats at the same level with
// the HP ratio preserved, plus move tier, shininess, held item, and fainted
// state carried over (buildPokemonInstance omits them).
function buildEvolvedInstance(instance, evolvedBase, newLevel) {
  const hpRatio = instance.stats.hp / instance.stats.maxHp
  const evolved = buildPokemonInstance(evolvedBase, newLevel)
  // Preserve HP ratio
  const evolvedHp = Math.max(1, Math.floor(evolved.stats.maxHp * hpRatio))
  // Preserve the Pokémon's current move tier across evolution (set via TM nodes,
  // not by level), using the evolved Pokémon's primary type.
  const preservedTier = instance.move?.tier ?? tierForLevel(newLevel)
  // Shininess carries through evolution — keep the flag and the matching sprites.
  const shiny = !!instance.shiny
  return {
    ...evolved,
    shiny,
    sprite:     shiny ? evolvedBase.shinySprite : evolvedBase.sprite,
    spriteBack: shiny ? evolvedBase.shinySpriteBack : evolvedBase.spriteBack,
    stats: { ...evolved.stats, hp: evolvedHp },
    // The evolved form re-picks its attacking type: an evolution can change
    // typing entirely (Charmeleon fire → Charizard fire/flying), so the
    // pre-evolution's choice may no longer apply.
    //
    // Asked of the EVOLVED species but with the carried held item, so a
    // Polarity Band survives the evolution. Reading attackTypeFor alone here
    // reverted the band's retype while the band stayed equipped.
    move: getTypeMove(
      currentMoveType({ pokeId: evolvedBase.pokeId, types: evolvedBase.types, heldItem: instance.heldItem ?? null }),
      preservedTier,
    ),
    // Carry the held item through evolution (buildPokemonInstance omits it).
    heldItem: instance.heldItem ?? null,
    fainted: instance.fainted,
  }
}

// Check if a Pokémon should evolve after reaching newLevel.
// `maxSpeciesId` gates options to the run region's generation (pass
// GEN_MAX_ID[config.generation]). Branches whose trigger isn't level-up
// (stones, trade, friendship) unlock at NON_LEVEL_EVO_LEVEL.
// `ignoreLevel` drops the level requirement entirely — used by the Evolve
// Stone item, which evolves a Pokémon on the spot regardless of level.
// Returns:
//   null                  — no eligible evolution
//   { evolved }           — exactly one eligible branch: the evolved instance
//   { options: [{ id }] } — several eligible branches: the UI must ask the
//                           player (EvolutionChoice), then call evolveInto()
export async function checkEvolution(instance, newLevel, { maxSpeciesId = Infinity, ignoreLevel = false } = {}) {
  try {
    if (!evoCache.has(instance.pokeId)) {
      await loadEvolutionLine(instance.pokeId)
    }
    const branches = evoCache.get(instance.pokeId) ?? []
    // The Evolve Stone (ignoreLevel) evolves anything. Otherwise: level-up
    // branches gate on their level; non-level-up branches (stone/trade/
    // friendship) auto-evolve ONLY for allowlisted species (Eevee) — every
    // other non-level evolver requires the Evolve Stone.
    const autoNonLevel = AUTO_EVOLVE_NONLEVEL.has(instance.pokeId)
    const eligible = branches.filter(b => {
      if (b.id > maxSpeciesId) return false
      if (ignoreLevel) return true
      if (b.levelUp) return newLevel >= b.minLevel
      return autoNonLevel && newLevel >= NON_LEVEL_EVO_LEVEL
    })
    if (eligible.length === 0) return null
    if (eligible.length > 1) return { options: eligible.map(b => ({ id: b.id })) }
    const evolvedBase = await fetchPokemonBase(eligible[0].id)
    return { evolved: buildEvolvedInstance(instance, evolvedBase, newLevel) }
  } catch {
    return null
  }
}

// Evolve a Pokémon into the species the player CHOSE in the EvolutionChoice
// popup (multi-branch lines — see checkEvolution). Returns the evolved
// instance, or null on failure.
export async function evolveInto(instance, speciesId) {
  try {
    const evolvedBase = await fetchPokemonBase(speciesId)
    return buildEvolvedInstance(instance, evolvedBase, instance.level)
  } catch {
    return null
  }
}

// Apply a battle victory to the sim's final team: level-ups, the 5% survivor
// heal, an optional full heal + revive (boss wins), then evolution checks.
// `maxSpeciesId` gates evolution options to the region's generation.
// Returns { roster, evolutionNotices, evolutionChoices }:
//   notices  — { from, to, pokeId } auto-evolutions (Pokédex "owned"
//              recording stays at the call site)
//   choices  — { index, fromId, fromName, sprite, options: [{ id }] } pending
//              player picks; those Pokémon stay un-evolved until evolveInto.
export async function applyBattleVictory(finalPlayerTeam, { levelsGained = 2, fullHeal = false, maxSpeciesId = Infinity } = {}) {
  // Levels are earned by taking part in the win. A Pokémon that fought and
  // fainted during the battle still levels up; only one that was ALREADY fainted
  // when the battle started (`_enteredFainted`) earns nothing — it never
  // participated, and has to be revived (Pokécenter / boss full-heal) first.
  // Older callers that don't set the flag fall back to the post-battle state.
  const earnedLevels = fp => (fp._enteredFainted !== undefined ? !fp._enteredFainted : !fp.fainted)
  let roster = finalPlayerTeam.map(fp => (fp._base && earnedLevels(fp)) ? levelUp(fp, fp._base, levelsGained) : fp)
  // Victory heal: every surviving Pokémon recovers a fraction of max HP (capped).
  const healPct = BALANCE.pokemon.victoryHealPct
  roster = roster.map(p =>
    p.fainted ? p
      : { ...p, stats: { ...p.stats, hp: Math.min(p.stats.maxHp, p.stats.hp + Math.round(p.stats.maxHp * healPct)) } }
  )
  if (fullHeal) {
    roster = roster.map(p => ({ ...p, fainted: false, stats: { ...p.stats, hp: p.stats.maxHp } }))
  }

  const evolutionNotices = []
  const evolutionChoices = []
  const nextRoster = []
  for (let i = 0; i < roster.length; i++) {
    const p = roster[i]
    const result = await checkEvolution(p, p.level, { maxSpeciesId })
    if (result?.options) {
      // Multi-branch line — the player picks via the EvolutionChoice popup
      // (evolveInto); until then the Pokémon stays un-evolved.
      evolutionChoices.push({ index: i, fromId: p.pokeId, fromName: p.name, sprite: p.sprite, options: result.options })
      nextRoster.push(p)
    } else if (result?.evolved) {
      evolutionNotices.push({ from: p.name, to: result.evolved.name, pokeId: result.evolved.pokeId, shiny: !!result.evolved.shiny })
      nextRoster.push(result.evolved)
    } else {
      nextRoster.push(p)
    }
  }
  return { roster: nextRoster, evolutionNotices, evolutionChoices }
}

// Level up a Pokémon instance — recalculates stats only.
// The move never changes on level-up; only a TM / Power Upgrade node changes it.
export function levelUp(instance, base, levels) {
  // Clamp at MAX_LEVEL — a full run's victories would otherwise push levels
  // past 100, where the stat formulas stop being meaningful. Already-capped
  // Pokémon keep their stats exactly (newLevel === level, so hpDiff is 0).
  const newLevel = Math.min(MAX_LEVEL, instance.level + levels)
  const newHp = calcHP(base.baseStats.hp, newLevel)
  const hpDiff = newHp - instance.stats.maxHp
  return {
    ...instance,
    level: newLevel,
    stats: {
      ...instance.stats,
      maxHp:   newHp,
      // Leveling raises max HP but must not revive a fainted Pokémon.
      hp:      instance.fainted ? 0 : Math.min(instance.stats.hp + hpDiff, newHp),
      attack:  calcStat(base.baseStats.attack,  newLevel),
      defense: calcStat(base.baseStats.defense, newLevel),
      spAtk:   calcStat(base.baseStats.spAtk,   newLevel),
      spDef:   calcStat(base.baseStats.spDef,   newLevel),
      speed:   calcStat(base.baseStats.speed,   newLevel),
    },
  }
}

// Rare Candy — level ONE roster member, then check it for an evolution.
//
// Distinct from applyBattleVictory, which levels the whole team: this targets a
// single index, grants no victory heal, and skips the `_enteredFainted` gate. A
// fainted Pokémon can be fed a candy — it levels and stays fainted (levelUp
// already refuses to revive), because the candy is not a heal.
//
// Returns the same { roster, used } contract the healing helpers use, plus the
// evolution notices and choices applyBattleVictory produces, so the caller can
// drive the same popups. `used: false` means the item did nothing and must be
// KEPT: that happens only at MAX_LEVEL, or on a Pokémon with no `_base` (which
// would make the stat recalculation impossible).
// Polarity Band — rebuild a Pokémon's move on its alternate type (`on`) or on
// its natural attacking type (`off`). Called when the band is equipped and
// again when it leaves, so the move never outlives the item that changed it.
//
// The move's TIER is preserved: TM upgrades are progress the player paid for
// and must survive an item swap. A single-type Pokémon has no alternate, so
// this returns it untouched — the band is inert rather than broken.
export function retypeMove(pokemon, on) {
  if (!pokemon) return pokemon
  const tier = pokemon.move?.tier ?? tierForLevel(pokemon.level)
  const alt = alternateTypeFor(pokemon.pokeId, pokemon.types)
  if (on && !alt) return pokemon
  const type = on ? alt : attackTypeFor(pokemon.pokeId, pokemon.types)
  return { ...pokemon, move: getTypeMove(type, tier) }
}

// The type a Pokémon's move should have RIGHT NOW, held items included.
//
// Every site that rebuilds a move must ask this rather than attackTypeFor
// directly. Equipping is not the only thing that rebuilds a move — evolution
// re-picks it (typing can change) and the TM node re-picks it (tier changes) —
// and both of those used to read the table alone. A band-wearing Pidgey that
// evolved, or a band-wearing Swampert given a TM, silently reverted to its
// natural type while the band stayed equipped and kept granting its ×1.25.
//
// `heldItem` is the whole difference. Anything that rebuilds `move` without
// consulting it will reintroduce that bug.
export function currentMoveType(pokemon) {
  if (!pokemon) return 'normal'
  if (pokemon.heldItem?.retype === 'move') {
    const alt = alternateTypeFor(pokemon.pokeId, pokemon.types)
    if (alt) return alt
  }
  return attackTypeFor(pokemon.pokeId, pokemon.types)
}

// Type Prism — collapse a dual-type Pokémon onto its alternate type, for good.
//
// This rewrites `types`, not just the move, so it changes DEFENSE as much as
// offense: a water/ground Swampert becomes pure Ground, shedding its 4x Grass
// weakness along with five resistances. Both halves of that trade are the point.
//
// The move is rebuilt to match, because a Pokémon whose displayed move type
// disagrees with its actual typing reads as a bug.
//
// Returns { roster, used } like the healing helpers. `used: false` means KEEP
// the item: a single-type Pokémon has no alternate, which is 209 of the 371
// species in the dex — the common case, not an edge case.
export function applyTypePrism(roster, index) {
  const target = roster[index]
  if (!target) return { roster, used: false }
  const alt = alternateTypeFor(target.pokeId, target.types)
  if (!alt) return { roster, used: false }

  return {
    roster: roster.map((p, i) => i === index ? {
      ...p,
      types: [alt],
      // Preserve the move's TIER (set by TM nodes, not by level) while retyping
      // it — the same rule evolution follows.
      move: getTypeMove(alt, p.move?.tier ?? tierForLevel(p.level)),
    } : p),
    used: true,
  }
}

export async function applyRareCandy(roster, index, levels, { maxSpeciesId = Infinity } = {}) {
  const target = roster[index]
  const none = { roster, used: false, evolutionNotices: [], evolutionChoices: [] }
  if (!target || !target._base) return none
  // Already capped — levelUp would return an identical instance, so consuming
  // the candy would destroy it for nothing.
  if (target.level >= MAX_LEVEL) return none

  const leveled = levelUp(target, target._base, levels)
  let next = roster.map((p, i) => (i === index ? leveled : p))

  // Same evolution pass the post-battle path runs, scoped to the one Pokémon
  // that changed. Multi-branch lines (Eevee, Tyrogue…) queue a choice instead
  // of evolving, exactly as they do after a win.
  const evolutionNotices = []
  const evolutionChoices = []
  // `options` is checked BEFORE `evolved`, matching applyBattleVictory: a
  // multi-branch result can carry both, and the player's choice must win over
  // an auto-evolution.
  const result = await checkEvolution(leveled, leveled.level, { maxSpeciesId })
  if (result?.options) {
    evolutionChoices.push({
      index,
      fromId: leveled.pokeId,
      fromName: leveled.name,
      sprite: leveled.sprite,
      options: result.options,
    })
  } else if (result?.evolved) {
    next = next.map((p, i) => (i === index ? result.evolved : p))
    evolutionNotices.push({
      from: leveled.name,
      to: result.evolved.name,
      pokeId: result.evolved.pokeId,
      shiny: !!result.evolved.shiny,
    })
  }

  return { roster: next, used: true, evolutionNotices, evolutionChoices }
}
